project_id = "pyngcobhnvzerpiuxwaa"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.analyze-documents]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = false
  [functions.generate-spv-documents]
    verify_jwt = false
  [functions.deploy-contract-suite]
    verify_jwt = false
  [functions.deploy-smart-contract]
    verify_jwt = false
  [functions.verify-contract]
    verify_jwt = false
  [functions.wire-contracts]
    verify_jwt = false
  [functions.verify-suite]
    verify_jwt = false
