import { mockScoreDimensions } from "@/data/mockSPVData";
import { mockSPV } from "@/data/mockDashboardData";
import { ScoreBar } from "./ScoreBar";

export function SPVAssetScore() {
  return (
    <div className="bg-card border border-border rounded-lg p-6 space-y-4">
      <div className="flex items-center justify-between mb-2">
        <h2 className="text-sm font-bold text-foreground uppercase tracking-wider">
          Asset Score™
        </h2>
        <div className="text-right">
          <div className="text-3xl font-extrabold text-primary">{mockSPV.creditScore}</div>
          <span className="text-[10px] text-muted-foreground tracking-wider uppercase">Standard Grade</span>
        </div>
      </div>
      <div className="space-y-2.5">
        {mockScoreDimensions.map((dim) => (
          <ScoreBar key={dim.name} label={dim.name} score={dim.score} weight={dim.weight} />
        ))}
      </div>
      <p className="text-[11px] text-muted-foreground pt-2 border-t border-border">
        Generated by Bakua AI Engine v2.1 · Ref: HS-MHCC-2025-001
      </p>
    </div>
  );
}
